### PR TITLE
fix(ui): polish template variable ux

### LINKED ISSUE #5381: Polish issues with source selection in template variables
- [x] Opening the variable model doesn't run the query and shows an error
 - [x] Switching source doesn't re-run the query
 - [x] Selecting a new source clears all selections
 - [x] Clipping on source drop down when choosing csv or map
      image-1

### PR DESCRIPTION
**Pull request by hoorayimhelping**
Closes #5381

* Coerces existing template variables into a variables with a dynamic source
* Correctly displays the values template variables with dynamic sources at query run time, not just creation time
* Correctly runs the meta query against the correct source database when creating a template variable.

## Testing Instructions
1. Checkout `16ac349228228c0370fb93535e6125ab548ae2aa` to get on the last version before the new template variable code was merged. `git checkout 16ac349`
1. Run chronograf and build the ui
1. Create a template variable. There should be no source dropdown
1. Checkout this branch. `git checkout bs_fix_source_template_query_error` (you might need to do `git checkout .` to ignore any changes to `yarn.lock`
1. The template variable you created before should have the proper values.
1. Edit the template variable you created before by clicking the gear icon.
1. You should see the dropdown with `Dynamic` listed.
1. Modify that as you wish and save it. It should work as expected.
1. Create a new template variable, it should work as expected and run the meta query.

  - [x] Rebased/mergeable
  - [x] Tests pass

### CODE REVIEW

File: chronograf.go [hunk 1]
```diff
@@ -187,7 +187,7 @@ type Template struct {
 	Type     string         `json:"type"`            // Type can be fieldKeys, tagKeys, tagValues, csv, constant, measurements, databases, map, influxql, text
 	Label    string         `json:"label"`           // Label is a user-facing description of the Template
 	Query    *TemplateQuery `json:"query,omitempty"` // Query is used to generate the choices for a template
-	SourceID int            `json:"sourceID,string"` // Source is the id of the data source
+	SourceID string         `json:"sourceID"`        // Source is the id of the data source
```
Comment (glinton) [inline chronograf.go]: I'm pretty sure it wasn't, but was this an int in any released version?

File: go.mod [hunk 2]
```diff
@@ -15,6 +15,7 @@ require (
 	github.com/elazarl/go-bindata-assetfs v1.0.0
 	github.com/gogo/protobuf v1.3.1
 	github.com/golang/groupcache v0.0.0-20191227052852-215e87163ea7 // indirect
+	github.com/golang/protobuf v1.3.3 // indirect
```
Comment (glinton) [inline go.mod]: This may be correct, but run a `go mod tidy` just to be sure.

Comment (hoorayimhelping) [reply go.mod]: ty ty, always forget that
