### PR TITLE
Fixes adding template variables breaks dashboard

### LINKED ISSUE #3241: Dashboards broken when adding a template variable
to reproduce, create a new dashboard and try to add a template variable. 

image

### LINKED ISSUE #3242: Update the broken text
- [ ] add a space before the here linke
- [ ] add a period to the end

### PR DESCRIPTION
**Pull request by bthesorceror**
Closes #3242
Closes #3241 

  - [x] Rebased/mergable
  - [x] Tests pass
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/dashboards/constants/templateControlBar.js [hunk 1]
```diff
@@ -1,13 +1,20 @@
...
 
 export const minDropdownWidth = 146
 export const maxDropdownWidth = 300
 export const dropdownPadding = 30
 
-export const calculateDropdownWidth = values => {
-  const longestValue = values.reduce(
-    (a, b) => (a.value.length > b.value.length ? a.value : b.value)
-  )
+const valueLength = a => {
```
Comment (121watts) [inline ui/src/dashboards/constants/templateControlBar.js]: Could you use _.size() here?

**Comment by 121watts** [comment]
super approved
