### PR TITLE
Fixes remaining bugs with multi slack handlers

### LINKED ISSUE #2855: Add ability to define multiple slack nodes in Kapacitor
connect https://github.com/influxdata/kapacitor/issues/1696

- [x] ensure that the latest changes hasn't broken the existing slack config in chronograf
- [x] add the ability to configure multiple slack integrations in chronograf

### PR DESCRIPTION
**Pull request by bthesorceror**
Closes #2855

  - [x] Rebased/mergeable
  - [x] Tests pass
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/kapacitor/components/config/SlackConfig.tsx [hunk 1]
```diff
@@ -183,29 +214,31 @@ class SlackConfig extends PureComponent<Props, State> {
   }
 
   private handleSubmit = async e => {
-    const {isNewConfig} = this.props
     e.preventDefault()
+
+    const {workspace} = this.state
```
Comment (jaredscheib) [inline ui/src/kapacitor/components/config/SlackConfig.tsx]: could you share your thoughts on why this would be from state as opposed to other state destructuring that has been modularized into getters?

File: ui/src/kapacitor/components/config/SlackConfig.tsx [hunk 2]
```diff
@@ -183,29 +214,31 @@ class SlackConfig extends PureComponent<Props, State> {
...
+
     const properties: SlackProperties = {
       url: this.url.value,
       channel: this.channel.value,
       enabled: this.state.enabled,
     }
+
     if (isNewConfig) {
-      properties.workspace = this.workspace.value
+      properties.workspace = workspace
```
Comment (jaredscheib) [inline ui/src/kapacitor/components/config/SlackConfig.tsx]: 1. a bit strange seeing a value on an object being assigned directly -- could a spread operator be used here?
1. also in the context of all of these getters, this reads a bit weird to me -- what do you think about `workspace` --> `this.workspace` and putting workspace behind a getter?

File: ui/src/kapacitor/components/config/SlackConfig.tsx [hunk 3]
```diff
@@ -183,29 +214,31 @@ class SlackConfig extends PureComponent<Props, State> {
...
+    const success = await this.props.onSave(properties, isNewConfig, workspace)
     if (success) {
       this.setState({testEnabled: true})
     }
   }
 
   private handleDelete = async e => {
     e.preventDefault()
-    await this.props.onDelete(this.workspace.value, this.workspaceID)
+    const {workspace} = this.state
```
Comment (jaredscheib) [inline ui/src/kapacitor/components/config/SlackConfig.tsx]: see question above about a possible getter

File: ui/src/kapacitor/components/config/SlackConfigs.tsx [hunk 4]
```diff
@@ -73,7 +74,7 @@ class SlackConfigs extends PureComponent<Props, State> {
             />
           )
         })}
-        {isMultipleConfigsSupported && (
+        {this.isAddAllowed && (
```
Comment (jaredscheib) [inline ui/src/kapacitor/components/config/SlackConfigs.tsx]: it's not clear to me what `isAddAllowed` would mean, semantically -- would you consider preserving some of the self-awareness around `config`, such as `isConfigAddAllowed`?

File: ui/src/kapacitor/components/config/SlackConfigs.tsx [hunk 5]
```diff
@@ -88,6 +89,14 @@ class SlackConfigs extends PureComponent<Props, State> {
     return this.state.configs
   }
 
+  private get isAddAllowed(): boolean {
+    const {isMultipleConfigsSupported} = this.props
+    const {configs} = this.state
+    const allExisting = _.every(configs, c => !this.isNewConfig(c))
```
Comment (jaredscheib) [inline ui/src/kapacitor/components/config/SlackConfigs.tsx]: could you clarify what `allExisting` refers to, such as `allExistingConfigs`?

File: ui/src/kapacitor/components/config/SlackConfigs.tsx [hunk 6]
```diff
@@ -99,7 +108,13 @@ class SlackConfigs extends PureComponent<Props, State> {
   private getWorkspace = (config: Config): string => {
     const {isMultipleConfigsSupported} = this.props
     if (isMultipleConfigsSupported) {
-      return get(config, 'options.workspace', 'new')
+      const workspace = _.get(config, 'options', {workspace: null}).workspace
```
Comment (jaredscheib) [inline ui/src/kapacitor/components/config/SlackConfigs.tsx]: interesting

File: ui/src/kapacitor/components/AlertTabs.tsx [hunk 7]
```diff
@@ -516,9 +516,16 @@ class AlertTabs extends PureComponent<Props, State> {
...
         return true
-      } catch ({
-        data: {error},
-      }) {
+      } catch (err) {
+        const {data} = err
+        const {error} = data
+        if (!error) {
+          this.props.notify(
+            notifyAlertEndpointSaveFailed(section, 'Cannot save configuration')
```
[the remark this answers is not in the document]
Comment (bthesorceror) [reply ui/src/kapacitor/components/AlertTabs.tsx]: we just get a 502 back from Kapa with no additional information.

File: ui/src/kapacitor/components/config/SlackConfig.tsx [hunk 8]
```diff
@@ -33,32 +35,26 @@ interface Props {
...
   private url: HTMLInputElement
   private channel: HTMLInputElement
-  private workspace: HTMLInputElement
 
   constructor(props) {
     super(props)
     this.state = {
       testEnabled: this.props.enabled,
       enabled: _.get(this.props, 'config.options.enabled', false),
+      workspace: _.get(this.props, 'config.options.workspace', '') || '',
```
[the remark this answers is not in the document]
Comment (bthesorceror) [reply ui/src/kapacitor/components/config/SlackConfig.tsx]: we get back a object that has {workspace: null} at this point so the _.get will just return the null and not the default since the key is present.

File: ui/src/kapacitor/components/config/SlackConfig.tsx (hunk 1 above)
Comment (bthesorceror) [reply ui/src/kapacitor/components/config/SlackConfig.tsx]: State is a little different to me than props, since there is no computed value needed I felt fine about destructuring from state.

File: ui/src/kapacitor/components/config/SlackConfig.tsx (hunk 2 above)
Comment (bthesorceror) [reply ui/src/kapacitor/components/config/SlackConfig.tsx]: we only want to send the workspace on create, for updates we want to omit the key altogether.
