### PR TITLE
Fix Gauge Resizing Bug

### LINKED ISSUE #2695: Gauges malfunctioning on Mac OS X/Safari and Chrome
Mac OS Version: 10.13.1 (17B1003)
Safari Version 11.0.1 (13604.3.5)

Resizing a cell with a gauge in it results in the gauge outside the cell, and the gauge type does not display properly in the query builder. 
safariscreensnapz039
safariscreensnapz038

Seems to work just fine on Chrome though

### PR DESCRIPTION
**Pull request by alexpaxton**
- [x] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x] Rebased/mergable
  - [x] Tests pass
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Closes #2695 

### The Problem
- Resizing any cell in a dashboard causes any gauge type cell to think it is being resized

### The Solution
- Give gauges the ability to detect whether their parent cell is the one currently being resized

### CODE REVIEW

**Comment by alexpaxton** [comment]
Wasn't able to reproduce the safari bug in which the gauge appeared outside a cell, but I did fix the resizing bug @russorat pointed out

File: ui/src/shared/components/GaugeChart.js [hunk 1]
```diff
@@ -35,11 +36,17 @@ class GaugeChart extends PureComponent {
     // When a new height is passed the Gauge component resizes internally
     // Passing in a new often ensures the gauge appears sharp
 
+    let thisGaugeIsResizing = false
+    if (resizeCoords) {
+      thisGaugeIsResizing = cellID === resizeCoords.i
```
Comment (ischolten) [inline ui/src/shared/components/GaugeChart.js]: Lines 39 - 42 could be shortened to one line.
