### PR TITLE
Fix histogram overflow issue when using basepath

### LINKED ISSUE #3968: Some overlap on the log viewer histogram
image

### PR DESCRIPTION
**Pull request by chnn**
Closes #3968

The `HistogramChart` uses SVG `clip-path=url(#some-element-id)` properties in it's implementation. With basepath enabled, Chronograf rewrites all instances of `url(` as `url(/basepath` when serving assets, which breaks these usages of `clip-path`.

This commit introduces a utility to properly encode urls in `clip-path` properties using a hacky workaround (dynamically render `url(` client-side so it's never rewritten by Chronograf). While we could address the issue server side (in `server/url_prefixer.go`), it's likely not worth it given the looming Chronograf 2.0 epoch.

See also https://github.com/influxdata/chronograf/pull/3402

### CODE REVIEW

File: ui/src/utils/svg.ts [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+  //
+  // Chronograf supports a [`--basepath`][0] option that rewrites all instances
+  // of `url(` occuring in asset files as they are served, which breaks usages
+  // of `url(#...)` strings in SVG elements. This issue has been fixed for
+  // standalone SVG files by [#3402][1], but not for inline SVG elements (i.e.
+  // those rendered by components). This workaround renders `url(#...)` strings
+  // dynamically on the client to evade the server asset rewriting.
+  //
+  // [0]: https://docs.influxdata.com/chronograf/v1.6/administration/config-options/#chronograf-service-options
+  // [1]: https://github.com/influxdata/chronograf/pull/3402
```
Comment (ebb-tide) [inline ui/src/utils/svg.ts]: whoa, so thorough! :)
