### PR TITLE
Pass uuid to proxy requests for determining which responses are relevant

### LINKED ISSUE #4111: Dashboard URLs - copying relative time over absolute time fails to update graph or controls
build **Nightly Build**

build time **201808040043**

Bowser **Chrome 68**

```
$ chronograf --version
2018/08/06 16:14:59 Chronograf 1.4.3.0~n201808040043 (git: 51d3e418b1eb0eefdd966a5fe5e239e5f4c89fe4)
```

_Use Case_

1. Create a dashboard and a graph with historic data of about a year old.
1. Set the time range for the graph to absolute values.  For example the lower calendar is 28 days in the past and the upper calendar is 14 days in the past. The graph is redrawn to show the new thresholds.
1. In the address bar paste in a URL with a relative value. e.g. ```http://localhost:8888/sources/2/dashboards/10?lower=now%28%29%20-%201h```
1. Press ENTER or use 'paste and go' to get the page to refresh. 

The graph fails to update as well as the current value in the time range control. 

_Expected Behavior_

That the graph will be updated when the page reloads.

_Screenshots_

urlrelativeoverabsolute01
urlrelativeoverabsolute02
urlrelativeoverabsolute03

_Notes_

Not sure if this is a regression.  Only came across this sequence today, as previously I was testing first with relative values and then absolute ones, which seems to work as expected.

### PR DESCRIPTION
**Pull request by bthesorceror**
Closes #4111

  - [x] Rebased/mergeable
  - [x] Tests pass
  - [x] swagger.json updated (if modified Go structs or API)
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: chronograf.go [hunk 1]
```diff
@@ -194,6 +194,7 @@ type Query struct {
 	GroupBys []string `json:"groupbys,omitempty"` // GroupBys collate the query by these tags
 	Label    string   `json:"label,omitempty"`    // Label is the Y-Axis label for the data
 	Range    *Range   `json:"range,omitempty"`    // Range is the default Y-Axis range for the data
+	UUID     string   `json:"uuid,omitempty"`
```
Comment (ischolten) [inline chronograf.go]: would you consider adding a comment to next to this added field to match the other ones and explain what its for?

File: server/influx.go [hunk 2]
```diff
@@ -24,6 +24,7 @@ func ValidInfluxRequest(p chronograf.Query) error {
 
 type postInfluxResponse struct {
 	Results interface{} `json:"results"` // results from influx
+	UUID    string      `json:"uuid,omitempty"`
```
Comment (ischolten) [inline server/influx.go]: same as above

File: ui/src/shared/components/time_series/TimeSeries.tsx [hunk 3]
```diff
@@ -46,6 +47,8 @@ const GraphLoadingDots = () => (
   </div>
 )
 class TimeSeries extends Component<Props, State> {
+  private lastestUUID: string = uuid.v1()
```
Comment (ischolten) [inline ui/src/shared/components/time_series/TimeSeries.tsx]: should this say `lastestUUID`?
