### PR TITLE
Fixes line graph data with strings errors

### LINKED ISSUE #3300: Uncaught Error: Expected number or array but got string
To reproduce, create a new dashboard, add a cell, and copy and paste the following query into the CEO.

`SELECT top("usage_active", host,30) FROM "telegraf"."autogen"."cpu" WHERE time > now() - 1m AND host =~ /rsavage/`

image

### LINKED ISSUE #3309: Uncaught Error: Expected number or array but got string
I think we should catch this error at least. it doesn't seem to degrade the user experience but we should still catch it.

image

### PR DESCRIPTION
**Pull request by bthesorceror**
Closes #3309
Closes #3300

  - [x] Rebased/mergeable
  - [x] Tests pass
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/shared/components/LineGraph.js [hunk 1]
```diff
@@ -26,14 +43,15 @@ class LineGraph extends Component {
...
-        nextProps.data,
-        nextProps.isInDataExplorer
-      )
+      this.parseTimeSeries(nextProps.data, nextProps.isInDataExplorer)
     }
   }
 
   render() {
+    if (!this.isValidData) {
+      return <InvalidData />
```
Comment (ebb-tide) [inline ui/src/shared/components/LineGraph.js]: should probably be a terniary?
