### PR TITLE
Flux builder fixes

### LINKED ISSUE #4465: Miscellaneous Flux builder bugs
When attempting to build a filter function, can't change filter type to `!=`:

can t change filter type to

Can't preview range query: 

can t preview range query

Inconsistent cursor state:

inconsistent cursor state

Script doesn't update when editing function fields (must press _Enter_ to update):

script and builder mismatch

Extra comma in `window` function editor:

extra comma in window node

### PR DESCRIPTION
**Pull request by chnn**
Closes #4465

- Addresses some of the issues in #4465—I'll open up issues for the remaining bits
- Also does some general clean up

See commits for details.

### CODE REVIEW

File: ui/src/flux/components/FuncArgsPreview.tsx [hunk 1]
```diff
@@ -41,23 +41,18 @@ export default class FuncArgsPreview extends PureComponent<Props> {
...
     const {args} = func
 
-    return args.map((arg, i): JSX.Element => {
-      if (!arg.value) {
-        return
-      }
+    return args.filter(a => a.value).map((arg, i) => {
+      let argValue = String(arg.value)
 
-      const separator = i === 0 ? null : ', '
```
Comment (bthesorceror) [inline ui/src/flux/components/FuncArgsPreview.tsx]: Why move this out of a variable, I think it makes the JSX a little harder to read below to have it inline.

Comment (chnn) [reply ui/src/flux/components/FuncArgsPreview.tsx]: I thought it was confusing that there was another `, ` used nearby that wasn't consuming the `separator` variable. I'll move it back and clarify the naming.
