### PR TITLE
Fix Jittery Template Variable Dropdowns

### LINKED ISSUE #3275: Template Variable Dropdowns are jittery
tempvar-dropdown-jitter

### PR DESCRIPTION
**Pull request by alexpaxton**
Closes #3275 

_Briefly describe your proposed changes:_
Ensure template variable dropdowns are sized correctly

_What was the problem?_
tempvar-dropdown-jitter
The dropdown's size isn't getting calculated correctly

_What was the solution?_
Pass the `value` key into `calculateSize` instead of passing the whole object

  - [ ] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x] Rebased/mergeable
  - [x] Tests pass
  - [ ] swagger.json updated (if modified Go structs or API)
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/dashboards/constants/templateControlBar.js [hunk 1]
```diff
@@ -1,16 +1,17 @@
...
-export const maxDropdownWidth = 300
+export const minDropdownWidth = 120
+export const maxDropdownWidth = 330
 export const dropdownPadding = 30
 
 const valueLength = a => _.size(a.value)
 
 export const calculateDropdownWidth = (values = []) => {
-  const longestValue = _.maxBy(values, valueLength)
+  const longest = _.maxBy(values, valueLength)
```
Comment (bthesorceror) [inline ui/src/dashboards/constants/templateControlBar.js]: the default for values is [] will this ever be the case? if so, then line 14 with throw an error because maxBy will return null.

**Comment by alexpaxton** [comment]
@bthesorceror just pushed a change that will set the dropdown to `minDropdownWidth` if there are no values or an empty array
