### PR TITLE
fix(kapacitor/alert): support .Time.Unix message validation #5492

### LINKED ISSUE #5492: Cannot use .Time.Unix in alert rule message template
Screenshot 2020-05-22 08 53 45

The editor reports an incorrect format, despite it being a valid attribute. We should allow for this to be set.

### PR DESCRIPTION
**Pull request by sranka**
Closes #5492 

_Briefly describe your proposed changes:_
_What was the problem?_
 {{.Time.Unix}} was reported as invalid in alert message template, although it is valid 
_What was the solution?_
The UI message validator was enhanced to support {{.Time.Unix}} and {{.Time.UnixNano}}

  - [ ] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x] Rebased/mergeable
  - [x] Tests pass
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/kapacitor/utils/alertMessageValidation.ts [hunk 1]
```diff
@@ -1,24 +1,33 @@
 import _ from 'lodash'
 import {RULE_MESSAGE_TEMPLATE_TEXTS} from 'src/kapacitor/constants'
 
+// the following template variables must also pass validation, see #5492
+// they are not that much common to be part of RULE_MESSAGE_TEMPLATE_TEXTS
+const EXTRA_MESSAGE_VARIABLES = ['.Time.Unix', '.Time.UnixNano']
```
Comment (glinton) [inline ui/src/kapacitor/utils/alertMessageValidation.ts:6]: should this be put into `src/kapacitor/constants` and imported?

File: ui/src/kapacitor/utils/alertMessageValidation.ts [hunk 2]
```diff
@@ -1,24 +1,33 @@
...
+
 export const isValidTemplate = (template: string): boolean => {
-  const exactMatch = !!_.find(RULE_MESSAGE_TEMPLATE_TEXTS, t => t === template)
+  if (
+    !!_.find(RULE_MESSAGE_TEMPLATE_TEXTS, t => t === template) ||
+    !!_.find(EXTRA_MESSAGE_VARIABLES, t => t === template)
+  ) {
+    return true
```
Comment (glinton) [inline ui/src/kapacitor/utils/alertMessageValidation.ts:13]: Seems like `returning true` here could cause a false positive. if an exact match occurs, returning would be fine, but if it is not an exact match (only contains a time variable) it seems that would be an invalid template. maybe?

File: ui/src/kapacitor/utils/alertMessageValidation.ts (hunk 1 above)
Comment (sranka) [reply ui/src/kapacitor/utils/alertMessageValidation.ts:6]: My preference is to keep the constants closer as much close to the code as possible, unless they are reused in multiple files ... which is not this case.

File: ui/src/kapacitor/utils/alertMessageValidation.ts (hunk 2 above)
Comment (sranka) [reply ui/src/kapacitor/utils/alertMessageValidation.ts:13]: Yes, it is an exact match here. UI only validates the [go template](https://golang.org/pkg/text/template/) with a pre-defined set of variables that are used by the server. And yes, there are more cases, in which UI validation may fail on a good template. This defect only helps a bit as requested, the time/value ratio for making this perfect for all possible cases is really high ... therefore regexp approach was chosen at the beginning and I am continuing to do so.
