### PR TITLE
Table/bug squashing

### LINKED ISSUE #3306: Uncaught TypeError: Cannot read property '0' of undefined
image

### LINKED ISSUE #3315: Not all lines displaying in line graphs
Notice that in this graph, there are 4 lines, but only two series listed in the legend.

image

This should show something like this where each series has it's own name and color in the legend:
screen shot 2018-04-25 at 2 17 47 pm

### PR DESCRIPTION
**Pull request by ebb-tide**
Closes #3306
Closes #3315

_Briefly describe your proposed changes:_
_What was the problem?_
_What was the solution?_

  - [ ] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [ ] Rebased/mergeable
  - [ ] Tests pass
  - [ ] swagger.json updated (if modified Go structs or API)
  - [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/utils/groupBy.js [hunk 1]
```diff
@@ -15,14 +18,14 @@ const groupByMap = (responses, responseIndex, groupByColumns) => {
             ...firstColumns.slice(1),
           ],
           groupByColumns,
-          name: _.get(responses, [0, 'series', 0, 'name']),
+          name: _.get(results, [0, 'series', 0, 'name']),
```
Comment (bthesorceror) [inline ui/src/utils/groupBy.js]: should this maybe default to an empty string?

File: ui/src/utils/groupBy.js [hunk 2]
```diff
@@ -35,13 +38,17 @@ const groupByMap = (responses, responseIndex, groupByColumns) => {
 const constructResults = (raw, groupBys) => {
   return _.flatten(
     map(raw, (response, index) => {
-      const responses = _.get(response, 'response.results', [])
+      const results = _.get(response, 'response.results', [])
+
+      const successfulResults = _.filter(
+        results,
+        r => !_.get(r, 'error', false)
```
Comment (bthesorceror) [inline ui/src/utils/groupBy.js]: what do you think about using `_.isNil(r.error)`?

File: ui/src/utils/groupBy.js [hunk 3]
```diff
@@ -92,11 +99,15 @@ const constructCells = serieses => {
         vals,
```
Comment (ischolten) [inline ui/src/utils/groupBy.js]: Not relevant to this pr but maybe something to consider: instead of `values || []` here, you can give values on line 91 a default value of [].

File: ui/src/utils/groupBy.js (hunk 2 above)
Comment (bthesorceror) [reply ui/src/utils/groupBy.js]: `r => _.isNil(r.error)`
