### PR TITLE
Fixes now() time parsing when requesting annotations

### LINKED ISSUE #3218: Error message parsing time "NaN" as "2006-01-02T15:04:05.999Z07:00"
This shows up in the CEO when i have a fixed time range set and one of the values is Now

`ERRO[0011] Error message parsing time "NaN" as "2006-01-02T15:04:05.999Z07:00": cannot parse "NaN" as "2006"  component=server http_status =422`

image

### PR DESCRIPTION
**Pull request by bthesorceror**
Closes #3218

  - [x] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x] Rebased/mergable
  - [x] Tests pass
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/dashboards/utils/time.ts [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+    return {since: Date.now() - seconds * 1000, until: null}
+  }
+
+  const since = Date.parse(lower)
+  let until
+  if (upper === 'now()') {
+    until = Date.now()
+  } else {
+    until = Date.parse(upper)
+  }
```
Comment (ebb-tide) [inline ui/src/dashboards/utils/time.ts]: I know you don't like terniary's, but wouldn't 
``` 
const upper = (upper==='now()')
? Date.now()
: Date.parse(upper)
```
look soooo much better? ;)

completely aesthetic pref. obvs.

File: ui/test/dashboards/utils/time.test.ts [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+        .subtract()
+        .seconds(10)
+        .unix()
+      const result = time.millisecondTimeRange(timeRange)
+
+      expect(result.since).toBeGreaterThanOrEqual(expectedSince)
+      expect(result.until).toBe(null)
+    })
+  })
+})
```
Comment (ebb-tide) [inline ui/test/dashboards/utils/time.test.ts]: love tests!
