### PR TITLE
Fix dismissal of overlay on uploading dashboards

### LINKED ISSUE #3939: Import dashboard automatically loading the json file with no option to confirm
to repro, try to import a dashboard. I think it's a side effect of the csv uploads

kapture 2018-07-17 at 9 20 25

### PR DESCRIPTION
**Pull request by 121watts**
Closes #3939

### CODE REVIEW

File: ui/src/dashboards/components/ImportDashboardOverlay.tsx [hunk 1]
```diff
@@ -54,12 +54,10 @@ class ImportDashboardOverlay extends PureComponent<Props, State> {
...
     fileName: string
   ): void => {
-    const {onImportDashboard, onDismissOverlay} = this.props
+    const {notify, onImportDashboard, onDismissOverlay} = this.props
     const fileExtensionRegex = new RegExp(`${this.validFileExtension}$`)
     if (!fileName.match(fileExtensionRegex)) {
-      this.props.notify(
-        notifyDashboardImportFailed(fileName, 'Please import a JSON file')
-      )
+      notify(notifyDashboardImportFailed(fileName, 'Please import a JSON file'))
```
Comment (ischolten) [inline ui/src/dashboards/components/ImportDashboardOverlay.tsx]: nice!
