### PR TITLE
fix(logs): fall back to point timestamp

### LINKED ISSUE #5472: Chronograf (1.8.2) Log viewer does not fall back to point timestamp
When viewing the logs in the log viewer where some entries do not specify a timestamp field, the timestamp column shows 01/01/1970, despite the log entries being ordered correctly based on the point time. Filtering with the graph still works, this seems to just be an issue with that column.

I use the tail input plugin with grok patterns to extract log events from formatted output, which does not insert a valid numeric timestamp field.

### PR DESCRIPTION
**Pull request by sranka**
Closes #5472

_Briefly describe your proposed changes:_
If no timestamp field is defined in the syslog measurement, point's time is used.  

_What was the problem?_
Null values were shown as 1970-01-01...  

_What was the solution?_
Null timestamp value is replaced by point's time value multiplied by 1_000_000 ( nanos are used by [telegram syslog input plugin](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/syslog/syslog.go#L382), but millis are used to represent time in the web UI ) 

  - [ ] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [ ] Rebased/mergeable
  - [x] Tests pass
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/logs/utils/table.ts [hunk 1]
```diff
@@ -174,8 +175,20 @@ export const applyChangesToTableData = (
...
   const columns = _.get(tableData, 'columns', [])
   const values = _.get(tableData, 'values', [])
-  const data = [columns, ...values]
 
+  // #5472 fallback to timestamp when time is not defined
+  const timeColumnIndex = _.indexOf(columns, 'time')
+  const timestampColumnIndex = _.indexOf(columns, 'timestamp')
+  if (timeColumnIndex >= 0 && timestampColumnIndex >= 0) {
+    // modify existing data to save memory
+    ;(values as TimeSeriesValue[][]).forEach(row => {
```
Comment (hoorayimhelping) [inline ui/src/logs/utils/table.ts:184]:
```suggestion
    values.forEach(row => {
```

File: ui/src/logs/utils/table.ts [hunk 2]
```diff
@@ -174,8 +175,20 @@ export const applyChangesToTableData = (
 ): TableData => {
   const columns = _.get(tableData, 'columns', [])
   const values = _.get(tableData, 'values', [])
```
Comment (hoorayimhelping) [inline ui/src/logs/utils/table.ts:177]:
```suggestion
  const values: TimeSeriesValue[][] = _.get(tableData, 'values', [])
```
