### PR TITLE
fix: zooming out stops presentation mode

### LINKED ISSUE #5382: Zooming on a graph in Presentation mode kicks you out of presentation mode
to repro, open a dashboard, click the button in the top right to open presentation mode, then try to zoom in on a graph. You are kicked back into the dashboard.

manually adding `present=true` to the url keeps you in presentation mode.

### PR DESCRIPTION
**Pull request by vlastahajek**
Closes #5382 

_Briefly describe your proposed changes:_
_What was the problem?_ Zooming out in presentation mode exits presentation mode
_What was the solution?_ disablePresenstationMode() event was dispatch every time location has been changed. Added filter to dispatch even only if path part changes

  - [X] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [X] Rebased/mergeable
  - [x] Tests pass

### CODE REVIEW

File: ui/src/index.tsx [hunk 1]
```diff
@@ -78,8 +78,15 @@ const browserHistory = useRouterHistory(createHistory)({
...
-  dispatch(disablePresentationMode())
+// pathname of last location change
+let lastPathname: Pathname
+
+browserHistory.listen(location => {
+  // disable presentation mode only if pathname changes, #5382
+  if (lastPathname !== location.pathname) {
+    dispatch(disablePresentationMode())
+  }
+  lastPathname = location.pathname
```
Comment (glinton) [inline ui/src/index.tsx:89]: Move this line up a line into the `if` block to prevent wasted work to re-assign the same value.

Comment (hoorayimhelping) [reply ui/src/index.tsx:89]: i would argue more important than not wasting cpu cycles is to make the intent clear that this should only be overwritten if they aren't equal.

Comment (vlastahajek) [reply ui/src/index.tsx]: Sorry, guys, for this stupid omission. Fixed.
