### PR TITLE
fix(ui): use the the available y-axis label

### LINKED ISSUE #5314: [Dashboards] Y Axis Label of cells disappears after first view
__Build__

```
$ chronograf --version
2019/11/11 13:37:08 Chronograf 201911082126~nightly (git: 0b0e4b8bf091356dfd5710a1addd48279886dc50)
```

Tested against a test cluster installed using the script found [here](https://github.com/influxdata/bonitoo-selenium/blob/master/src/test/resources/infrastructure/setup_test_environment_enterprise_version.sh)

__Use  Case__ 

1. Create a new cell in a new dashboard 
1. Build an influx query for the cell 
1. Close the cell with the green check - Note that the cell has an auto generated y-axis label 
1. View Data Explorer
1. View Dashboards again
1. Open the recently created dashboard 

_The Y Axis label of the cell has disappeared_

__Expected Behavior__

That the Y axis label would be displayed, just as after creating the cell. 

__Screencast__

DashboardYAxis01

__Notes__

This seems to be happening when the Title property under Visualizations is set to Auto (y-axis title).

Previously, this was not an issue and the element `div.dygraph-label.dygraph-ylabel` was added to the cell with the title property set to Auto.

### PR DESCRIPTION
**Pull request by hoorayimhelping**
Closes #5314

y-axis labels were disappearing. This is a band-aid to fall back to a known value for the y-axis
  - [x] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x] Rebased/mergeable
  - [x] Tests pass

### CODE REVIEW

File: ui/src/shared/components/Dygraph.tsx [hunk 1]
```diff
@@ -459,8 +459,11 @@ class Dygraph extends Component<Props, State> {
   }
 
   private getLabel = (axis: string): string => {
-    const {axes, queries} = this.props
-    const label = getDeep<string>(axes, `${axis}.label`, '')
+    const {axes, labels, queries} = this.props
+
+    // if label comes back as '', use the y axis label from props.labels
+    // see https://github.com/influxdata/chronograf/issues/5314
+    const label = getDeep<string>(axes, `${axis}.label`, '') || labels[1]
```
Comment (Asalem1) [inline ui/src/shared/components/Dygraph.tsx]: How can we be certain that `label` will have a length greater than 0?

Comment (hoorayimhelping) [reply ui/src/shared/components/Dygraph.tsx]: @Asalem1 fixed this
