### PR TITLE
Update Kapacitor config files to TS and minor OpsGenie Tab bug fix

### LINKED ISSUE #3145: Clicking the OpsGenie Tab on the Kapacitor Alerts configuration page causes an error
Error: Uncaught TypeError: Cannot read property 'length' of undefined

### LINKED ISSUE #3146: Deleting a team or recipient from the OpsGenie Tab on the Kapacitor Alerts Page doesn't persist

### PR DESCRIPTION
**Pull request by ischolten**
Closes #3146
Closes #3145

_Briefly describe your proposed changes:_
Converting files relating to Kapacitor Configs to typescript.
Fix undefined bug when clicking on OpsGenie tab (#3146)
Fix bug so that deleting a team or recipient in OpsGenie config persists (#3145)

_What was the problem?_
Files were in javascript, also there were a few bugs.

_What was the solution?_
Convert files to typescript and eliminate found bugs.

  - [x] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x] Rebased/mergable
  - [x] Tests pass
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/kapacitor/components/config/OpsGenieConfig.tsx [hunk 1]
```diff
@@ -115,21 +102,63 @@ class OpsGenieConfig extends Component {
...
-  }).isRequired,
-  onSave: func.isRequired,
-  onTest: func.isRequired,
-  enabled: bool.isRequired,
+  private get currentTeams(): Item[] {
+    const {currentTeams} = this.state
+    return currentTeams.map(team => ({name: team}))
+  }
+
+  private get currentRecipients(): Item[] {
```
Comment (jaredscheib) [inline ui/src/kapacitor/components/config/OpsGenieConfig.tsx]: see above

File: ui/src/shared/components/TagInput.tsx [hunk 2]
```diff
@@ -47,16 +38,29 @@ class TagInput extends Component {
...
     )
   }
-}
 
-const {arrayOf, func, string} = PropTypes
+  private handleAddTag = e => {
+    if (e.key === 'Enter') {
+      e.preventDefault()
+      const newItem = e.target.value.trim()
+      const {tags, onAddTag} = this.props
```
Comment (jaredscheib) [inline ui/src/shared/components/TagInput.tsx]: why not destructure `disableTest` as well?

File: ui/src/shared/components/TagInput.tsx [hunk 3]
```diff
@@ -47,16 +38,29 @@ class TagInput extends Component {
...
-  tags: arrayOf(string).isRequired,
-  title: string.isRequired,
-  disableTest: func,
+      this.input.value = ''
+      onAddTag(newItem)
+      this.props.disableTest()
+    }
+  }
+
+  private handleDeleteTag = item => {
```
Comment (jaredscheib) [inline ui/src/shared/components/TagInput.tsx]: typed inputs?

File: ui/src/shared/components/TagInput.tsx [hunk 4]
```diff
@@ -47,16 +38,29 @@ class TagInput extends Component {
...
+    this.props.onDeleteTag(item)
+  }
+
+  private shouldAddToList(item, tags) {
```
Comment (jaredscheib) [inline ui/src/shared/components/TagInput.tsx]: typed inputs and outputs?

File: ui/src/shared/components/TagInput.tsx [hunk 5]
```diff
@@ -1,34 +1,25 @@
...
-      this.input.value = ''
-      onAddTag(newItem)
-      this.props.disableTest()
-    }
-  }
-
-  handleDeleteTag = item => {
-    this.props.onDeleteTag(item)
-  }
+interface Item {
```
Comment (jaredscheib) [inline ui/src/shared/components/TagInput.tsx]: seems like it would be better to choose either text or name and enforce that usage everywhere, without it being conditional, if possible

File: ui/src/kapacitor/components/config/RedactedInput.tsx [hunk 6]
```diff
@@ -31,7 +37,7 @@ class RedactedInput extends Component {
             id={id}
             type="hidden"
             ref={refFunc}
-            defaultValue={defaultValue}
+            defaultValue={defaultValue.toString()}
```
Comment (jaredscheib) [inline ui/src/kapacitor/components/config/RedactedInput.tsx]: if this is undefined or a boolean it seems like it'll convert to `'true'` or `'false'` or will fail if it's undefined, no?

File: ui/src/kapacitor/components/config/PagerDutyConfig.tsx [hunk 7]
```diff
@@ -80,20 +86,28 @@ class PagerDutyConfig extends Component {
...
-  config: shape({
-    options: shape({
-      'service-key': bool.isRequired,
-      url: string.isRequired,
-    }).isRequired,
-  }).isRequired,
-  onSave: func.isRequired,
-  onTest: func.isRequired,
-  enabled: bool.isRequired,
+  private refFunc = r => {
```
Comment (jaredscheib) [inline ui/src/kapacitor/components/config/PagerDutyConfig.tsx]: could this be made the same as in the other components?

File: ui/src/kapacitor/components/config/SMTPConfig.tsx [hunk 8]
```diff
@@ -54,7 +71,7 @@ class SMTPConfig extends Component {
             id="smtp-port"
             type="text"
             ref={r => (this.port = r)}
-            defaultValue={port || ''}
+            defaultValue={port.toString() || ''}
```
Comment (jaredscheib) [inline ui/src/kapacitor/components/config/SMTPConfig.tsx]: if this is already enforced as a string type, why the need to convert it?

File: ui/src/kapacitor/components/config/SMTPConfig.tsx [hunk 9]
```diff
@@ -1,36 +1,53 @@
...
+}
+
+interface Config {
+  options: {
+    host: string
+    port: number
+    username: string
+    password: boolean
+    from: string
+    to: string
```
Comment (jaredscheib) [inline ui/src/kapacitor/components/config/SMTPConfig.tsx]: why is this not an array?

File: ui/src/shared/components/ConfirmButton.tsx [hunk 10]
```diff
@@ -0,0 +1,119 @@
...
+            >
+              {confirmText}
+            </div>
+          </div>
+        </div>
+      </ClickOutside>
+    )
+  }
+
+  private handleButtonClick = () => {
```
Comment (jaredscheib) [inline ui/src/shared/components/ConfirmButton.tsx]: think it'd be worthwhile having a type on the input to ensure that these types of functions only are used for click handlers etc.?

File: ui/src/shared/components/ConfirmButton.tsx [hunk 11]
```diff
@@ -0,0 +1,119 @@
+import React, {PureComponent} from 'react'
+import {ClickOutside} from 'src/shared/components/ClickOutside'
+
+interface Props {
```
Comment (jaredscheib) [inline ui/src/shared/components/ConfirmButton.tsx]: all of these being conditional seems like some further refactoring would be useful

File: ui/src/shared/components/Tabs.tsx [hunk 12]
```diff
@@ -4,11 +4,11 @@ import classnames from 'classnames'
 
 interface TabProps {
   children: JSX.Element[] | JSX.Element
-  onClick: () => void
-  isDisabled: boolean
-  isActive: boolean
-  isKapacitorTab: boolean
-  isConfigured: boolean
+  onClick?: () => void
```
Comment (jaredscheib) [inline ui/src/shared/components/Tabs.tsx]: seems like all of these being conditional is a bit funky

File: ui/src/kapacitor/components/config/AlertaConfig.tsx [hunk 13]
```diff
@@ -105,22 +115,28 @@ class AlertaConfig extends Component {
...
+    if (success) {
+      this.setState({testEnabled: true})
+    }
+  }
+
+  private disableTest = () => {
+    this.setState({testEnabled: false})
+  }
+
+  private handleTokenRef = r => (this.token = r)
```
[the remark this answers is not in the document]
Comment (ischolten) [reply ui/src/kapacitor/components/config/AlertaConfig.tsx]: The Input or InputFieldName defined in Kapacitor.ts is what i defined. It's technically doing the same thing but I will change it to use the HTMLInputElement in order to type it more correctly.

File: ui/src/types/kapacitor.ts [hunk 14]
```diff
@@ -186,3 +186,16 @@ interface DBRP {
   db: string
   rp: string
 }
+
+// Input represents the values from an input field in the Kapacitor Configs
+export interface Input {
```
[the remark this answers is not in the document]
Comment (ischolten) [reply ui/src/types/kapacitor.ts]: I will remove these since they will no longer be used. Instead i will use HTMLInputElement

File: ui/src/types/kapacitor.ts [hunk 15]
```diff
@@ -186,3 +186,16 @@ interface DBRP {
...
+  value: string
+}
+
+export interface Checkbox {
```
[the remark this answers is not in the document]
Comment (ischolten) [reply ui/src/types/kapacitor.ts]: Also removing for the same reason as above

File: ui/src/kapacitor/components/config/AlertaConfig.tsx [hunk 16]
```diff
@@ -105,22 +115,28 @@ class AlertaConfig extends Component {
...
+      url: this.url.value,
+    }
+
+    const success = await this.props.onSave(properties)
+    if (success) {
+      this.setState({testEnabled: true})
+    }
+  }
+
+  private disableTest = () => {
```
[the remark this answers is not in the document]
Comment (ischolten) [reply ui/src/kapacitor/components/config/AlertaConfig.tsx]: yes

File: ui/src/kapacitor/components/config/AlertaConfig.tsx [hunk 17]
```diff
@@ -105,22 +115,28 @@ class AlertaConfig extends Component {
...
-      environment: string,
-      origin: string,
-      token: bool,
-      url: string,
-    }).isRequired,
-  }).isRequired,
-  onSave: func.isRequired,
-  onTest: func.isRequired,
-  enabled: bool.isRequired,
+  private handleSubmit = async e => {
```
[the remark this answers is not in the document]
Comment (ischolten) [reply ui/src/kapacitor/components/config/AlertaConfig.tsx]: output type is inferred to be void

File: ui/src/kapacitor/components/config/AlertaConfig.tsx [hunk 18]
```diff
@@ -1,39 +1,49 @@
...
-class AlertaConfig extends Component {
-  constructor(props) {
-    super(props)
-    this.state = {
-      testEnabled: this.props.enabled,
-    }
+interface Properties {
+  environment: string
+  origin: string
+  token: string
```
[the remark this answers is not in the document]
Comment (ischolten) [reply ui/src/kapacitor/components/config/AlertaConfig.tsx]: The actual value being passed in is a string and that is what gets saved into the DB. But because that field is redacted, it is passed as a boolean in config to indicate whether there is a value or not.

File: ui/src/kapacitor/components/config/AlertaConfig.tsx [hunk 19]
```diff
@@ -1,39 +1,49 @@
...
+  url: string
+}
+
+interface Config {
+  options: {
+    environment: string
+    origin: string
+    token: boolean
```
[the remark this answers is not in the document]
Comment (ischolten) [reply ui/src/kapacitor/components/config/AlertaConfig.tsx]: see above

File: ui/src/kapacitor/components/config/AlertaConfig.tsx [hunk 20]
```diff
@@ -1,39 +1,49 @@
...
   }
+}
 
-  handleSubmit = async e => {
-    e.preventDefault()
+interface Props {
+  config: Config
+  onSave: (properties: Properties) => void
+  onTest: (event: React.MouseEvent<HTMLButtonElement>) => void
+  enabled: boolean
```
[the remark this answers is not in the document]
Comment (ischolten) [reply ui/src/kapacitor/components/config/AlertaConfig.tsx]: Enabled from props refers to whether that Alert Configuration is enabled. The testEnabled in state uses whether the component is enabled to determine if the testEnabled button should be made available.

File: ui/src/kapacitor/components/config/OpsGenieConfig.tsx [hunk 21]
```diff
@@ -115,21 +102,63 @@ class OpsGenieConfig extends Component {
...
-    options: shape({
-      'api-key': bool,
-      teams: array,
-      recipients: array,
-    }).isRequired,
-  }).isRequired,
-  onSave: func.isRequired,
-  onTest: func.isRequired,
-  enabled: bool.isRequired,
+  private get currentTeams(): Item[] {
```
[the remark this answers is not in the document]
Comment (ischolten) [reply ui/src/kapacitor/components/config/OpsGenieConfig.tsx]: That makes sense. It is now currentTeamsForTags and currentRecipientsForTags

File: ui/src/kapacitor/components/config/AlertaConfig.tsx (hunk 17 above)
[the remark this answers is not in the document]
Comment (jaredscheib) [reply ui/src/kapacitor/components/config/AlertaConfig.tsx]: and what about typing e to ensure it's only handling events?

File: ui/src/kapacitor/components/config/RedactedInput.tsx (hunk 6 above)
Comment (ischolten) [reply ui/src/kapacitor/components/config/RedactedInput.tsx]: defaultValue in an input must be a string or array of strings.

Comment (jaredscheib) [reply ui/src/kapacitor/components/config/RedactedInput.tsx]: but then might we end up with an incorrect default value? such as the strings `true`, `false`, or `undefined`? seems like the guard should be higher up in the chain to prevent incorrect values from reaching this point

File: ui/src/kapacitor/components/config/SMTPConfig.tsx (hunk 8 above)
Comment (ischolten) [reply ui/src/kapacitor/components/config/SMTPConfig.tsx]: Port is a number but defaultValue requires a string

File: ui/src/shared/components/ConfirmButton.tsx (hunk 11 above)
Comment (ischolten) [reply ui/src/shared/components/ConfirmButton.tsx]: the ?: means its an optional prop. if it has just the :, then it's required.

File: ui/src/shared/components/Tabs.tsx (hunk 12 above)
Comment (ischolten) [reply ui/src/shared/components/Tabs.tsx]: see above

Comment (jaredscheib) [reply ui/src/shared/components/Tabs.tsx]: responded above as well
