### PR TITLE
fix: validate oauth settings prior to starting

### LINKED ISSUE #5450: Do not start chronograf with incomplete auth settings
If Chronograf finds configuration for OAUTH or other authentication modes but that configuration is incomplete, shutdown chronograf.  Currently, the server starts without authentication enabled at all. It should fail to start.

### PR DESCRIPTION
**Pull request by glinton**
Closes #5450

_What was the problem?_
If there were any missing oauth settings, chronograf would start without authentication.
_What was the solution?_
If oauth settings are only partially added, an error is logged and chronograf fails to start.

  - [x] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x] Rebased/mergeable
  - [x] Tests pass

### CODE REVIEW

File: server/server.go [hunk 1]
```diff
@@ -124,42 +126,160 @@ type Server struct {
...
 	}
 }
 
 // UseGithub validates the CLI parameters to enable github oauth support
-func (s *Server) UseGithub() bool {
-	return s.TokenSecret != "" && s.GithubClientID != "" && s.GithubClientSecret != ""
+func (s *Server) UseGithub() error {
+	errMsg := []string{}
+
+	switch {
```
Comment (hoorayimhelping) [inline server/server.go:141]: stylistic nit (may not be applicable to golang):

`switch` statements (to me at least) usually imply a `default` case, but the default cause here is to execute the function, which makes these more like [guard clauses,](https://wiki.c2.com/?GuardClause) and it seems like this would be better as two `if` statements, since they both early return anyway.

File: server/server_test.go [hunk 2]
```diff
@@ -73,3 +75,73 @@ func Test_validBasepath(t *testing.T) {
...
+			err: "missing Auth0 oauth setting[s]: client secret",
+		},
+		{
+			desc: "test invalid google config (no token or clientSecret or publicUrl)",
+			s: &Server{
+				GoogleClientID: "abc123",
+			},
+			err: "missing Google oauth setting[s]: token secret, client secret, public url",
+		},
+	}
```
Comment (hoorayimhelping) [inline server/server_test.go:141]: these tests are off the chain!
