### PR TITLE
Fix table time as horizontal

### LINKED ISSUE #3801: Selecting horizontal table causes an error
table

```
Error: "Invalid size returned for cell 0 of value NaN"
valuehttp://chronograf.internal/app.d22b98355b1a04501e9e.js:47:33596valuehttp://chronograf.internal/app.d22b98355b1a04501e9e.js:47:35127valuehttp://chronograf.internal/app.d22b98355b1a04501e9e.js:47:35657valuehttp://chronograf.internal/app.d22b98355b1a04501e9e.js:47:34757valuehttp://chronograf.internal/app.d22b98355b1a04501e9e.js:47:37881valuehttp://chronograf.internal/app.d22b98355b1a04501e9e.js:32:16442valuehttp://chronograf.internal/app.d22b98355b1a04501e9e.js:32:14485updateClassInstancehttp://chronograf.internal/app.d22b98355b1a04501e9e.js:210:49387beginWorkhttp://chronograf.internal/app.d22b98355b1a04501e9e.js:210:51272ahttp://chronograf.internal/app.d22b98355b1a04501e9e.js:210:55246ohttp://chronograf.internal/app.d22b98355b1a04501e9e.js:210:55525Ehttp://chronograf.internal/app.d22b98355b1a04501e9e.js:210:58468bhttp://chronograf.internal/app.d22b98355b1a04501e9e.js:210:58011_http://chronograf.internal/app.d22b98355b1a04501e9e.js:210:57848interactiveUpdateshttp://chronograf.internal/app.d22b98355b1a04501e9e.js:210:74535Enhttp://chronograf.internal/app.d22b98355b1a04501e9e.js:210:28643 app.d22b98355b1a04501e9e.js:210:54065
```

### PR DESCRIPTION
**Pull request by 121watts**
Closes #3801 

_What was the problem?_
The `columnWidths` object did not include / consider that times could be columns.  

_What was the solution?_
Add times to the `columnWidths` object when they are in the 'topRow'.

### Notes
Debugging this issue makes me sad.  There is SO much untested code that does SO much data transformation.  I have no idea if my solution breaks something else.

@russorat I recommend that we put aside dev time to test the `utils/tableGraph` at a minimum.

### CODE REVIEW

File: ui/src/dashboards/utils/tableGraph.ts [hunk 1]
```diff
@@ -100,14 +100,16 @@ const updateMaxWidths = (
       const {widths: Widths} = maxColumnWidths
       const maxWidth = _.get(Widths, `${columnLabel}`, 0)
 
-      if ((isTopRow || currentWidth > maxWidth) && _.isString(columnLabel)) {
+      if (isTopRow || currentWidth > maxWidth) {
```
Comment (OfTheDelmer) [inline ui/src/dashboards/utils/tableGraph.ts]: ahh just a little line to go track down
