### PR TITLE
Bugfix/tempvar autoinsert buttons

### LINKED ISSUE #3807: TempVar replacement fails when adding tempVar from autocomplete options
screen shot 2018-06-29 at 18 02 37
screen shot 2018-06-29 at 18 02 59
screen shot 2018-06-29 at 18 03 25

### PR DESCRIPTION
**Pull request by ebb-tide**
Closes #3807 

_What was the problem?_
clicking on tempVar suggestion buttons would cause an onBlur event in the enclosing textArea, and an execution of the query, before the click event could properly edit the query text. 

_What was the solution?_
call the function to replace query text at onMouseDown rather than onClick, which runs before the onBlur event fires, editing query text, before query execution. 

  - [ ] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x] Rebased/mergeable
  - [x] Tests pass

### CODE REVIEW

File: ui/src/dashboards/components/QueryTextArea.tsx [hunk 1]
```diff
@@ -28,27 +48,78 @@ class QueryTextArea extends Component {
...
+    } = this.state
+
+    return (
+      <div className="query-editor">
+        <textarea
+          className="query-editor--field"
+          onChange={this.handleChange}
+          onKeyDown={this.handleKeyDown}
+          onBlur={this.handleUpdate}
+          ref={this.handleTextAreaRef}
```
Comment (bthesorceror) [inline ui/src/dashboards/components/QueryTextArea.tsx]: Could we change this to use a react 16 refObject?

Comment (ebb-tide) [reply ui/src/dashboards/components/QueryTextArea.tsx]: thanks! done.
