### PR TITLE
Miscellaneous data explorer refactoring and bug fixes

### LINKED ISSUE #4312: Data Explorer says string "FOO BAR" is syntactically correct Influx QL
bulid **Nightly Build**

bulid time **201808290031**

```
$ chronograf --version
2018/08/29 14:09:58 Chronograf 1.4.3.0~n201808290031 (git: 5b37ab634fa1899f2f9ed016bc3d36b31ee08bdf)
```

*Use Case*

1. Open _Explorer_
1. Enter the string "FOO BAR" into the query edit text area.  Nothing gets highlighted. 
1. click _Submit Query_

After a while a message appears.  "Your query is syntactically correct but returned no results"

*Question*

Is the string "FOO BAR" in fact syntactically correct?  The same can be asked of the string "bad_query" used in selenium tests. 

*Expected Behavior*

That if a statement is not syntactically correct, then it should be flagged as such, and to save resources, perhaps not been submitable. 

The previous message returned for this test case was "received status code 400 from server: err: error parsing query: found bad_query".  "Error parsing query" is more accurate than implying that the string is "syntactically correct".  If it were syntactically correct then it would be parsable. 

*Screenshots*

syntacticallycorrectinfuxql01
syntacticallycorrectinfuxql02

### PR DESCRIPTION
**Pull request by chnn**
Closes #4312

Lots of miscellaneous stuff here, it's probably easiest to review commit by commit.

Fixes a few bugs:

- Avoid issuing a separate request to analyze a query duration if the query does not contain the `:interval:` template variable
- Show query loading status immediately, rather than after the query duration has been analyzed
- Propagate query parsing errors to the UI (fix #4312)

Does a bunch of cleanup:

- Removed lots of `try` / `catch` blocks that existed purely to log an error and then rethrow it (errors get logged anyway)
- Lift `editQueryStatus` side effect out of the queries API code
- Reuse existing query API utilities in `downloadTimeseriesCSV`
- Other general cleanup

I found two more errors in the process, which I have filed as separate issues (#4375, #4376).

### CODE REVIEW

File: ui/src/shared/apis/query.ts [hunk 1]
```diff
@@ -1,113 +1,73 @@
...
-import {Template} from 'src/types'
-
-const noop = () => ({
-  type: 'NOOP',
-  payload: {},
-})
+import {Source, Template} from 'src/types'
+import {TimeSeriesResponse} from 'src/types/series'
 
+// REVIEW: why is this different than the `Query` in src/types?
```
Comment (alexpaxton) [inline ui/src/shared/apis/query.ts]: My guess is that this concept of a "query" relates to the UI. It is checking what the user has selected to decide whether or not it can display a complete query string from the builder

Not sure though!

**Comment by alexpaxton** [comment]
This all sounds great, but I think someone else may be better suited to review this than myself

File: ui/src/shared/components/time_series/TimeSeries.tsx [hunk 2]
```diff
@@ -278,6 +267,39 @@ class TimeSeries extends Component<Props, State> {
...
+
+      const warningMessage = extractQueryWarningMessage(response)
+
+      if (warningMessage) {
+        editQueryStatus(query.id, {warn: warningMessage})
+      } else {
+        editQueryStatus(query.id, {success: 'Success!'})
+      }
+
+      return {response}
```
Comment (OfTheDelmer) [inline ui/src/shared/components/time_series/TimeSeries.tsx]: I like this wrapping here
