### PR TITLE
Fix/New sources CLI and Deprecation

### LINKED ISSUE #2659: failed to retrieve default organization
## Bug report

```
# chronograf -v
2017/12/27 05:27:48 Chronograf 1.4.0.0 (git: e9dfbfcea003ed768a90cef0148a811942653d71)
```

### Details:

Upgraded from chronograf 1.3.10.0 to 1.4.0.0 and started getting the above error. My init script uses the `--new-sources=` option to specify my influx and kapacitor source. Haven't setup or specified any organizations. I get the same error with a fresh install as well. If I leave out the "--new-sources=" option, every thing runs ok and I can manually add the source from the web ui but the "--new-sources=" option still remains broken.

### Logs:

```
time="2017-12-27T04:03:23Z" level=error msg="failed to retrieve default organization" component=server new-sources=invalid
2017/12/27 04:03:23 failed to retrieve default organization
```

### PR DESCRIPTION
**Pull request by ischolten**
- [ ] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [ ] Rebased/mergable
  - [x] Tests pass
  - [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Resolves #2659

### CODE REVIEW

File: server/sources.go [hunk 1]
```diff
@@ -328,6 +330,8 @@ func (s *Service) HandleNewSources(ctx context.Context, input string) error {
 		return nil
 	}
 
+	s.Logger.Error("--new-sources is depracated. To preconfigure a source, see this link. www.example.com")
```
Comment (jaredscheib) [inline server/sources.go]: Should this say `www.example.com`, @russorat ?

Comment (russorat) [reply server/sources.go]: filed https://github.com/influxdata/chronograf/issues/2854 to address
