### PR TITLE
Fix template variable replacement within regexes

### LINKED ISSUE #3979: Template variables not being single quoted correctly

### PR DESCRIPTION
**Pull request by chnn**
Closes #3979 

Template variables used within regexes would not replace correctly when the query contained a `/` before the regex in the query, e.g. the following query breaks:

```
SELECT last("max") from (SELECT max("total")/1073741824 FROM "telegraf".."mem" WHERE "cluster_id" = :Cluster_Id: AND (host =~ /.*data.*/ OR host =~ /tot-.*-(3|4)/) GROUP BY time(1s), host)
```

This commit rewrites the logic for replacing template variables. It uses an iterative approach, since the `RegExp.match` used in the past has shown to be too unpredictable.

### CODE REVIEW

File: ui/src/tempVars/utils/replace.ts [hunk 1]
```diff
@@ -110,26 +110,58 @@ const renderTemplate = (query: string, template: Template): string => {
...
+    )
+
+    i = findRegexEnd(result, regexStart)
+  }
+
+  return result
+}
+
+const findRegexStart = (query: string, startIndex: number): number => {
+  return startIndex + query.slice(startIndex, query.length).indexOf('/')
```
Comment (ebb-tide) [inline ui/src/tempVars/utils/replace.ts]: I think you can omit the second argument to slice since it goes to the end of the string.  
but actually, `.indexOf` also takes an optional startIndex so line 151 may be equivalent to `query.indexOf('/', startIndex)`

File: ui/src/tempVars/utils/replace.ts [hunk 2]
```diff
@@ -110,26 +110,58 @@ const renderTemplate = (query: string, template: Template): string => {
...
+}
+
+const findRegexEnd = (query: string, startIndex: number): number => {
+  return startIndex + 1 + query.slice(startIndex + 1, query.length).indexOf('/')
```
Comment (ebb-tide) [inline ui/src/tempVars/utils/replace.ts]: this looks a lot like `findRegexStart` maybe a single function called `findNext..` called with `startIndex` or `startIndex+1` would be easier to reason about?

File: ui/src/tempVars/utils/replace.ts [hunk 3]
```diff
@@ -110,26 +110,58 @@ const renderTemplate = (query: string, template: Template): string => {
...
+}
+
+const replaceSubstring = (s: string, i: number, j: number, content: string) => {
+  // Replace everything in `s` from indices `i` up to but not including `j` with `content`
+  const split = s.split('')
+
+  split.splice(i, j - i + 1, ...content.split(''))
```
Comment (ebb-tide) [inline ui/src/tempVars/utils/replace.ts]: do you not like lodash?  especially for array operations, I think it's so much easier to reason with and makes one hate JS less?
```firstBit= _.join(_.slice(split, 0, i))```
```lastBit = _.join(_.slice(split, j+1))```
```return '${firstBit}${content}${lastBit}'```

I still hated JS, but maybe tiny bit better?

Comment (chnn) [reply ui/src/tempVars/utils/replace.ts]: seems much clearer, will change
